CREATE TABLE "T_S"
(
  X integer NOT NULL,
  Y integer NOT NULL
);

CREATE TABLE "T_A22"
(
  X integer NOT NULL
);

CREATE TABLE "T_R"
(
  X integer NOT NULL,
  Y integer NOT NULL
);

CREATE TABLE "T_A1"
(
  X integer NOT NULL
);

INSERT INTO "T_A1" VALUES (4);
INSERT INTO "T_R" VALUES (3,4);
INSERT INTO "T_R" VALUES (2,3);
INSERT INTO "T_R" VALUES (1,2);

INSERT INTO "T_A22" VALUES (13);
INSERT INTO "T_S" VALUES (12,13);
INSERT INTO "T_S" VALUES (1,12);

INSERT INTO "T_A1" VALUES (108);
INSERT INTO "T_R" VALUES (107,108);
INSERT INTO "T_R" VALUES (106,107);
INSERT INTO "T_R" VALUES (105,106);
INSERT INTO "T_R" VALUES (104,105);
INSERT INTO "T_R" VALUES (103,104);
INSERT INTO "T_R" VALUES (102,103);
INSERT INTO "T_R" VALUES (101,102);

INSERT INTO "T_A22" VALUES (113);
INSERT INTO "T_S" VALUES (112,113);
INSERT INTO "T_S" VALUES (101,112);

